services:
  postgres-auth-local:
    image: postgres:16
    container_name: postgres-auth-local
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: authdb-local
    ports:
      - "5050:5432"
    volumes:
      - postgres-data-local:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME} -d authdb-local"]
      interval: 10s
      timeout: 5s

      retries: 5

volumes:
  postgres-data-local:

networks:
  app-network:
    name: auth-service-local
    driver: bridge

