spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/authdb"
    username: "${SPRING_DATASOURCE_USERNAME}"
    password: "${SPRING_DATASOURCE_PASSWORD}"
    driver-class-name: org.postgresql.Driver

  flyway:
    validate-on-migrate: true
    enabled: true
    locations: "classpath:db/migration"
    schemas: toxic_bet
    default-schema: toxic_bet

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_schema: toxic_bet

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${G_CLIENT_ID}"
            client-secret: "${G_CLIENT_SECRET}"
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:2300/auth-server/login/oauth2/code/google"

logging:
  level:
    org.flywaydb: INFO
    org.apache.zookeeper: OFF

server:
  servlet:
    context-path: /auth-server
  port: 2300
  forward-headers-strategy: framework

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

resend:
  api:
    key: "${RESEND_API_KEY}"
    url: "https://api.resend.com/emails"
  sender: "${RESEND_EMAIL}"

integration:
  toxicbet:
    users:
      base-url: "http://toxic-bet-api:20000"

frontend:
  origin: "http://localhost:4200"
  oauth-callback-path: "/login-callback"